easy_admin:
   entities:
       User:
            class: App\Entity\User
            new:
                fields:
                    - 'fullname'
                    - 'email'
                    - 'password'
                    - {property: 'image', type: 'file'}
    #    - App\Entity\User
