easy_admin:
    design:
        menu:
            
            - {entity: 'User', icon: 'id-card-o', label: 'Utilisateurs'}
            - {entity: 'Note', icon: 'pencil', label: 'Note des élèves'}
            # - {entity: 'Matter', icon: 'newspaper-o', label: 'Matières'}