easy_admin:
    design:
        menu:
            
            - {entity: 'User', icon: 'user', label: 'Utilisateurs'}
            # - {entity: 'Category', icon: 'newspaper-o', label: 'Categories'}
            # - {entity: 'Tag', icon: 'tags', label: 'Tags'}