easy_admin:
    design:
        menu:
            
            - {entity: 'User', icon: 'id-card-o', label: 'Utilisateurs'}

            - label: 'Cours'
              icon: 'newspaper-o'
              children:
                    - {entity: 'Note', icon: 'pencil', label: 'Note des élèves'}
                    - {entity: 'Matter', icon: 'newspaper-o', label: 'Matières'}