easy_admin:
    entities:
        Note:
            class: App\Entity\Note
            list:
                fields:
                    - {property: 'matter', label: 'Matières'}
                    - {property: 'user', label: 'Utilisateurs'}
                    - {property: 'note', label: 'Notes'}
                    - {property: 'message', label: 'Messages'}

                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

            form:
                fields:
                    - {property: 'matter', label: 'Matière'}
                    - {property: 'user', label: "Etudiant assigné"}
                    - {property: 'note', label: 'Note'}
                    - {property: 'message', label: 'Remarque'}
