easy_admin:
    user:
        display_name: true
        display_avatar: false
        name_property_path: 'fullname'

    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\EasyyAdminController
            list:
                fields:
                    - { property: 'fullname', type: 'string', label: 'Nom complet' }
                    - 'email'
                    - 'password'
                    - { property: 'image', type: 'image', base_path: '%uploads_path%', label: 'Photo' }
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%uploads_path%' }
                    - { property: 'imageFile', type: 'file' }

            form:
                fields:
                    - 'fullname'
                    - 'email'
                    - { property: 'password', type: 'password', algorithm: 'auto' }
                    # - { property: 'image', type: 'image', base_path: '/images/products' }   
                    - { property: 'imageFile', type: 'vich_image' }

            
    #    - App\Entity\User